query SearchReposWithQuery {
  search(query: "repo:wasmedge/wasmedge", type: REPOSITORY, first: 100) {
    repositoryCount
    nodes {
      ... on Repository {
        url
        stargazers {
          totalCount
        }
        owner {
          avatarUrl
        }
        description
        readme: object(expression: "HEAD:README.md") {
          ... on Blob {
            text
          }
        }
        languages(first: 1, orderBy: {field: SIZE, direction: DESC}) {
          nodes {
            name
          }
        }
      }
    }
  }
}



query SearchReposWithQuery {
  search(
    query: "repo:jaykchen/the_tracker"
    type: REPOSITORY
    first: 100
  ) {
    repositoryCount
    nodes {
      ... on Repository {
        url
        stargazers {
          totalCount
        }
        owner {
          avatarUrl
        }
        description
        readme: object(expression: "HEAD:README.md") {
          ... on Blob {
            text
          }
        }
      }
    }
  }
}