query ($query: String!) {
  search(query: $query, type: ISSUE, first: 1, after: null) {
    issueCount
    nodes {
      ... on Issue {
        title
        url
        body
        author {
          login
        }
        repository {
          url
          stargazers {
            totalCount
          }
          owner {
            avatarUrl
          }
        }
        labels(first: 10) {
          nodes {
            name
          }
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}

{
  "query": "label:hacktoberfest is:issue is:closed created:2023-10-01..2023-10-03 -label:spam -label:invalid",
  "firstComments": 10,
  "firstTimelineItems": 10
}

{
  "query": "label:hacktoberfest is:issue is:open no:assignee created:2023-10-01..2023-10-03 -label:spam -label:invalid",
  "firstComments": 10,
  "firstTimelineItems": 10
}
#   Author: author:<username>
# Milestone: milestone:<milestone>
# Assignee: assignee:<username>
# Commenter: commenter:<username>
# Created: created:<date>
# Updated: updated:<date>
# Closed: closed:<date>
# Labels: label:<label>
# Projects: project:<project>
# Reactions: reactions:<reaction>
# Review requests: review-requested:<username>
# Review comments: review-commenter:<username>
# You can combine multiple filter conditions using the following operators:

# AND: condition1 condition2
# OR: condition1 OR condition2
# NOT: NOT condition