query GetIssues {
    nodes(ids: ["I_kwDOKVEIrM51XBav", "I_kwDOKcZWFs51WphI"]) {
      ... on Issue {
        url
        assignees(first: 5) {
          nodes {
            name
          }
        }
        comments(first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {
          nodes {
            author {
              login
            }
            body
            updatedAt
          }
        }
      }
    }
  }

{
ids: ["I_kwDOKVEIrM51XBav", "I_kwDOKcZWFs51WphI"]
}

