query GetMultipleIssues {
    nodes(ids: ["I_kwDOKVEIrM51XBav", "I_kwDOKcZWFs51WphI"]) {
      ... on Issue {
        url
        assignees {
          totalCount
        }
        comments(first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {
          nodes {
            author {
              login
            }
            body
            updatedAt
          }
        }
      }
    }
  }