query SearchPr($query: String!) {
  search(query: $query, type: ISSUE, first: 100, after: null) {
    issueCount
    nodes {
      ... on PullRequest {
        title
        url
        author {
          login
        }
        labels(first: 10) {
          nodes {
            name
          }
        }
        reviews(first: 5, states: [APPROVED]) {
          nodes {
            author {
              login
            }
            state
          }
        }
        mergedBy {
          login
        }
        mergedAt
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}

{
  "query": "label:hacktoberfest is:pr is:merged created:>2023-10-01 merged:2023-10-03T05:00:00..2023-10-03T09:00:00 -label:spam -label:invalid"
}
